import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";
import { ModalProvider } from "@/context/ModalContext";
import ModalManager from "@/components/modals/ModalManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  subsets:["latin"],
  weight:["100", "300", "400", "700", "900"],
})

export const metadata = {
  title: "Winnies Shoes and Bags",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>


        <AuthProvider>
         <ModalProvider>
          <ModalManager/>
          <Navbar />
          {children}
          <Footer />
      </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
